export const caseStudies = [
  {
    slug: 'llm-evaluation',
    number: '01',
    category: 'LLM & Generative AI',
    title: 'Evaluating confident answers before they become costly mistakes',
    problem: 'Generative AI can sound certain while being factually wrong, unsafe, incomplete, or subtly misleading.',
    action: 'Applied a four-part framework—Relevance, Safety, Accuracy, and Readability—using primary-source checks, language matching, and explicit hallucination flags.',
    result: 'Produced consistent benchmark data that helped teams improve response quality and reduce hallucinations across model pipelines.',
    resultShort: 'Sharper benchmarks, fewer hallucinations.',
    tags: ['ChatGPT', 'Perplexity', 'Yandex AI', 'Hallucination detection'],
  },
  {
    slug: 'search-quality',
    number: '02',
    category: 'Search Quality & SxS',
    title: 'Turning ambiguous search results into clear ranking decisions',
    problem: 'Search systems need human judgment to determine whether competing results truly satisfy nuanced user intent.',
    action: 'Conducted Page Quality Evaluation and Side-by-Side comparisons across SinSig 2.0 and SinSig Global, weighing usefulness, authority, freshness, and relevance.',
    result: 'Delivered precise rating datasets that informed algorithm adjustments and improved the quality of search experiences.',
    resultShort: 'Human judgment, translated into ranking signal.',
    tags: ['PQE', 'Side-by-Side', 'SinSig 2.0', 'Search intent'],
  },
  {
    slug: 'multilingual',
    number: '03',
    category: 'Multilingual Data Annotation',
    title: 'Catching the meaning that literal translation misses',
    problem: 'Automated translation often misses regional idioms, cultural context, and subtle intent shifts in non-English queries.',
    action: 'Performed image, freshness, and music relevance judging in Turkish and English, combining native context with deliberate cross-checking.',
    result: 'Strengthened cross-lingual model understanding and improved the reliability of localized search results.',
    resultShort: 'Better context across languages.',
    tags: ['Turkish', 'English', 'Localization', 'Relevance judging'],
  },
  {
    slug: 'trendyol',
    number: '04',
    category: 'E-commerce Strategy',
    title: 'A performance-led digital marketing analysis for Trendyol',
    problem: 'Global e-commerce growth demands a balance of mobile performance, localization, acquisition, and channel efficiency.',
    action: 'Analyzed traffic, social engagement, email strategy, advertising allocation, load speed, and affiliate programs, then shaped recommendations around mobile-first growth.',
    result: 'Produced a data-led strategy connecting localized campaigns, creator partnerships, content, and targeted mobile media.',
    resultShort: 'A clearer path from traffic to trust.',
    tags: ['SEO', 'Digital marketing', 'E-commerce', 'Performance analysis'],
    sampleUrl: 'https://docs.google.com/document/d/17kTY55HVFM4iue16VUV07veDXLh0DqJW/edit?usp=sharing&ouid=103117090966400388934&rtpof=true&sd=true',
  },
  {
    slug: 'italian-brands',
    number: '05',
    category: 'International Market Analysis',
    title: 'Il Segreto del Successo Italiano',
    problem: 'Understanding enduring Italian brands requires looking beyond commerce to heritage, craft, scarcity, and regional identity.',
    action: 'Authored an Italian-language analysis of family-business history, regional specialization, artisan loyalty, raw-material quality, and sustainability.',
    result: 'Delivered a culturally grounded market study demonstrating B2 Italian, analytical writing, and international brand strategy.',
    resultShort: 'Culture decoded as competitive advantage.',
    tags: ['Italian B2', 'Brand strategy', 'Cultural analysis', 'Research'],
    sampleUrl: 'https://drive.google.com/file/d/1brKrpLOF2HR40-K1ANIPyAFSZkg_sq8r/view?usp=sharing',
  },
]

export const galleryItems = [
  {
    src: '/assets/gallery/search-quality-profile.png',
    title: 'Search Engine Quality Specialist Profile & Projects',
    category: 'Professional evidence',
    aspect: 'wide',
  },
  {
    src: '/assets/gallery/trendyol-marketing-analysis.png',
    title: 'Trendyol Marketing Analysis',
    category: 'E-commerce case study',
    aspect: 'wide',
  },
  {
    src: '/assets/gallery/italian-success-intro.png',
    title: 'Il Segreto del Successo Italiano',
    category: 'Italian-language research',
    aspect: 'wide',
  },
]
